//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PongNet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PongDBEntities : DbContext
    {
        public PongDBEntities()
            : base("name=PongDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Score> ScoreSet { get; set; }

        public bool uniqueValue(int value)
        {
            foreach (Score score in ScoreSet)
            {
                if (score.Value == value)
                    return false;
            }
            return true;
        }
    }
}
